sonar.projectKey=supply-chain-demo
sonar.projectName=Supply Chain Demo
sonar.sources=app
sonar.exclusions=**/*.md,**/node_modules/**,**/nginx.conf
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=app/index.html
sonar.sourceEncoding=UTF-8
