sonar.projectKey=supply-chain-demo
sonar.projectName=Supply Chain Demo
sonar.sources=app
sonar.exclusions=**/*.md,**/node_modules/**,**/nginx.conf,**/plausible.js
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=app/index.html,app/plausible.js
sonar.sourceEncoding=UTF-8
